[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v
filterwarnings =
    ignore:.*Using `httpx` with `starlette.testclient` is deprecated.*
    ignore:.*The anyio.abc.BlockingPortal alias is deprecated.*
