#!/usr/bin/env python3
"""
DNS Threat Intelligence Functional Verification & Demonstration Tool
=====================================================================
Phase 2.7 — Run 0.16 (Real Output / Dashboard Readiness Test)

Usage:
    python scripts/test_threat_intelligence.py --domain example.com
    python scripts/test_threat_intelligence.py --matrix
    python scripts/test_threat_intelligence.py --golden

Strict Evidence Classification:
    LOCAL            - Resolved from local database (Tranco / URLhaus SQLite/PG)
    REAL             - Resolved from live external API provider (VirusTotal / OTX)
    MOCK / FIXTURE   - Recorded synthetic response for controlled regression test
    NO_DATA          - Provider queried successfully but has no record (404 / 0 pulses)
    PROVIDER FAILURE - Network timeout, rate limit (429), or 5xx server error
    COMPUTED         - Verdict, risk, and confidence generated by Correlation Engine
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sqlite3
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import tldextract
from dotenv import load_dotenv

# Set project root and paths
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "bind converter"))
sys.path.insert(0, str(PROJECT_ROOT / "parsing logs"))
sys.path.insert(0, str(PROJECT_ROOT / "feature extraction"))

# Load environment configuration
load_dotenv(PROJECT_ROOT / "api.env", override=False)
load_dotenv(PROJECT_ROOT / ".env", override=False)

# Suppress verbose loggers for clean report output
logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("requests").setLevel(logging.WARNING)
logging.getLogger("labeler").setLevel(logging.WARNING)

from labeler.config import LabelingConfig
from labeler.intel.manager import is_trusted
from labeler.intel.malicious import is_malicious
from labeler.intel.providers.virustotal import VirusTotalProvider
from labeler.intel.providers.alienvault import AlienVaultOTXProvider
from labeler.intel.correlation.engine import CorrelationEngine
from labeler.intel.correlation.models import ThreatDecision, ThreatProviderResult
from labeler.intel.correlation.scoring import WeightedScorer
from labeler.intel.reputation import get_domain as get_reputation_domain
from dashboard_aggregation.config import DASHBOARD_DB_PATH


# ---------------------------------------------------------------------------
# Normalization Helper
# ---------------------------------------------------------------------------
def normalize_domain(raw_domain: str) -> Dict[str, str]:
    """Normalize a domain string and extract registered domain and TLD."""
    cleaned = raw_domain.strip().lower().rstrip(".")
    ext = tldextract.extract(cleaned)
    registered_domain = (
        getattr(ext, "top_domain_under_public_suffix", None)
        or getattr(ext, "registered_domain", "")
        or cleaned
    )
    tld = ext.suffix
    subdomain = ext.subdomain
    return {
        "fqdn": cleaned,
        "registered_domain": registered_domain,
        "tld": tld,
        "subdomain": subdomain,
    }


# ---------------------------------------------------------------------------
# Investigation Engine
# ---------------------------------------------------------------------------
class ThreatIntelligenceInvestigator:
    def __init__(self, config: Optional[LabelingConfig] = None):
        self.config = config or LabelingConfig()
        self.online_config = self.config.get_online_ti_config()

    def evaluate_local(self, norm: Dict[str, str]) -> Dict[str, Any]:
        """Evaluate domain against local intelligence sources with scope preservation."""
        fqdn = norm["fqdn"]
        reg = norm["registered_domain"]
        
        # STEP 1 — EXACT FQDN MALICIOUS MATCH (URLhaus)
        if fqdn and fqdn != reg and is_malicious(fqdn):
            return {
                "verdict": "KNOWN_MALICIOUS",
                "source": "LOCAL (URLhaus)",
                "match_scope": "EXACT_FQDN",
                "matched_domain": fqdn,
                "tranco": {"matched": False, "status": "NO_DATA", "classification": "LOCAL"},
                "urlhaus": {"matched": True, "status": "KNOWN_MALICIOUS (EXACT_FQDN)", "classification": "LOCAL"},
            }

        # STEP 2 — TRANCO POPULARITY CONTEXT
        tranco_match = (reg and is_trusted(reg)) or (fqdn and is_trusted(fqdn))
        if tranco_match:
            is_root_art = (fqdn == reg and is_malicious(reg))
            scope = "ROOT_ARTIFACT" if is_root_art else "POPULARITY_CONTEXT"
            return {
                "verdict": "POPULAR_BENIGN_CONTEXT",
                "source": "LOCAL (Tranco)",
                "match_scope": scope,
                "matched_domain": reg or fqdn,
                "tranco": {"matched": True, "status": "POPULARITY_CONTEXT (TRANCO_MATCH)", "classification": "LOCAL"},
                "urlhaus": {"matched": is_root_art, "status": "SUPPRESSED_ROOT_ARTIFACT" if is_root_art else "NO_DATA", "classification": "LOCAL"},
            }

        # STEP 3 — UNTRUSTED REGISTERED DOMAIN FALLBACK (URLhaus)
        if reg and is_malicious(reg):
            scope = "EXACT_FQDN" if fqdn == reg else "REGISTERED_DOMAIN"
            return {
                "verdict": "KNOWN_MALICIOUS",
                "source": "LOCAL (URLhaus)",
                "match_scope": scope,
                "matched_domain": reg,
                "tranco": {"matched": False, "status": "NO_DATA", "classification": "LOCAL"},
                "urlhaus": {"matched": True, "status": f"KNOWN_MALICIOUS ({scope})", "classification": "LOCAL"},
            }

        # STEP 4 — UNKNOWN
        return {
            "verdict": "UNKNOWN",
            "source": "NO_DATA",
            "match_scope": None,
            "matched_domain": None,
            "tranco": {"matched": False, "status": "NO_DATA", "classification": "LOCAL"},
            "urlhaus": {"matched": False, "status": "NO_DATA", "classification": "LOCAL"},
        }

    def evaluate_external_live(self, domain: str) -> List[ThreatProviderResult]:
        """Perform live queries to configured external providers."""
        results: List[ThreatProviderResult] = []

        # VirusTotal
        vt = VirusTotalProvider(self.online_config)
        if vt.is_enabled():
            try:
                vt_res = vt.lookup(domain)
                results.append(vt_res)
            except Exception as exc:
                results.append(
                    ThreatProviderResult(
                        provider="VirusTotal",
                        unavailable=True,
                        error=str(exc),
                    )
                )
            finally:
                vt.close()

        # AlienVault OTX
        otx = AlienVaultOTXProvider(self.online_config)
        if otx.is_enabled():
            try:
                otx_res = otx.lookup(domain)
                results.append(otx_res)
            except Exception as exc:
                results.append(
                    ThreatProviderResult(
                        provider="AlienVault OTX",
                        unavailable=True,
                        error=str(exc),
                    )
                )
            finally:
                otx.close()

        return results

    def correlate(
        self,
        domain: str,
        provider_results: List[ThreatProviderResult],
    ) -> ThreatDecision:
        """Run correlation engine over provider results."""
        weights = {
            "VirusTotal": float(self.online_config.get("WEIGHT_VT", 0.60)),
            "AlienVault OTX": float(self.online_config.get("WEIGHT_OTX", 0.40)),
        }
        scorer = WeightedScorer(
            weights=weights,
            threshold=float(self.online_config.get("MALICIOUS_THRESHOLD", 0.60)),
        )
        score, confidence, is_malicious = scorer.calculate(provider_results)

        return ThreatDecision(
            domain=domain,
            malicious=is_malicious,
            score=score,
            confidence=confidence,
            threshold=scorer.threshold,
            provider_results=provider_results,
        )

    def check_persistence(self, domain: str) -> Dict[str, Any]:
        """Check presence of domain across PostgreSQL and SQLite read models."""
        pg_reputation = False
        pg_data = None
        try:
            pg_data = get_reputation_domain(domain)
            pg_reputation = pg_data is not None
        except Exception:
            pg_reputation = False

        # SQLite dashboard.db check
        sqlite_details = False
        sqlite_row = None
        if DASHBOARD_DB_PATH.exists():
            try:
                conn = sqlite3.connect(str(DASHBOARD_DB_PATH))
                conn.row_factory = sqlite3.Row
                cur = conn.cursor()
                cur.execute("SELECT * FROM domain_details WHERE domain = ?", (domain,))
                row = cur.fetchone()
                if row:
                    sqlite_details = True
                    sqlite_row = dict(row)
                conn.close()
            except Exception:
                sqlite_details = False

        return {
            "postgresql_reputation": pg_reputation,
            "postgresql_data": pg_data,
            "sqlite_dashboard_db": sqlite_details,
            "sqlite_data": sqlite_row,
        }

    def investigate(
        self,
        domain: str,
        override_provider_results: Optional[List[ThreatProviderResult]] = None,
        fixture_tag: Optional[str] = None,
        force_external: bool = False,
    ) -> Dict[str, Any]:
        """Execute full investigation on a domain with evidence scope."""
        start_time = time.perf_counter()
        norm = normalize_domain(domain)
        local_res = self.evaluate_local(norm)

        # External TI: skipped if local match is authoritative (unless forced or overridden)
        if override_provider_results is not None:
            provider_results = override_provider_results
            ext_tag = fixture_tag or "MOCK / FIXTURE"
        elif local_res["verdict"] in ("KNOWN_MALICIOUS", "POPULAR_BENIGN_CONTEXT") and not force_external:
            provider_results = []
            ext_tag = "SKIPPED (Local Authoritative Match)"
        else:
            provider_results = self.evaluate_external_live(norm["fqdn"])
            ext_tag = "REAL"

        # Correlation
        decision = self.correlate(norm["fqdn"], provider_results)

        # Derive final human verdict & scope
        if local_res["verdict"] == "KNOWN_MALICIOUS":
            final_verdict = "KNOWN_MALICIOUS"
            verdict_source = local_res["source"]
            verdict_scope = local_res["match_scope"]
            reason = f"Listed in URLhaus malware database (Scope: {verdict_scope}, Matched: {local_res['matched_domain']})"
        elif decision.malicious:
            final_verdict = "KNOWN_MALICIOUS"
            verdict_source = f"EXTERNAL ({ext_tag})"
            verdict_scope = "CORRELATED"
            reason = f"Correlated score ({decision.score:.2f}) exceeds threshold ({decision.threshold:.2f})"
        elif local_res["verdict"] == "POPULAR_BENIGN_CONTEXT":
            final_verdict = "POPULAR_BENIGN_CONTEXT"
            verdict_source = "LOCAL (Tranco)"
            verdict_scope = local_res["match_scope"]
            reason = f"Top-ranked global domain in Tranco database (Scope: {verdict_scope})"
        elif decision.has_intelligence and not decision.malicious:
            final_verdict = "KNOWN_CLEAN"
            verdict_source = f"EXTERNAL ({ext_tag})"
            verdict_scope = "EXTERNAL_PROVIDER"
            reason = "Queried across threat providers with zero malicious signals"
        else:
            final_verdict = "REVIEW_NEEDED / UNKNOWN"
            verdict_source = "INCONCLUSIVE"
            verdict_scope = "LEGACY / UNKNOWN"
            reason = "No authoritative local or external intelligence found"

        # Persistence check
        persist_status = self.check_persistence(norm["fqdn"])

        duration_ms = (time.perf_counter() - start_time) * 1000.0

        return {
            "domain": norm["fqdn"],
            "normalization": norm,
            "local": local_res,
            "external_tag": ext_tag,
            "provider_results": provider_results,
            "decision": decision,
            "final_verdict": final_verdict,
            "verdict_source": verdict_source,
            "verdict_scope": verdict_scope,
            "reason": reason,
            "persistence": persist_status,
            "duration_ms": duration_ms,
        }


# ---------------------------------------------------------------------------
# Formatting & Display
# ---------------------------------------------------------------------------
def print_investigation_report(inv: Dict[str, Any]) -> None:
    """Print clean, professional threat intelligence report with evidence scope."""
    d = inv["domain"]
    norm = inv["normalization"]
    local = inv["local"]
    ext_tag = inv["external_tag"]
    prs = inv["provider_results"]
    dec: ThreatDecision = inv["decision"]
    pers = inv["persistence"]

    print("=" * 68)
    print(" DNS THREAT INTELLIGENCE — INVESTIGATION RECORD")
    print("=" * 68)
    print(f" Domain:               {d}")
    print(f" Registered Domain:    {norm['registered_domain']}")
    print(f" TLD / Suffix:         {norm['tld'] or 'None'}")
    print(f" Execution Duration:   {inv['duration_ms']:.2f} ms")
    print("-" * 68)
    print(" [1] LOCAL INTELLIGENCE")
    print("-" * 68)
    print(f"   Tranco Whitelist  : {local['tranco']['status']} [{local['tranco']['classification']}]")
    print(f"   URLhaus Malicious : {local['urlhaus']['status']} [{local['urlhaus']['classification']}]")
    print(f"   Resolved Scope    : {inv['verdict_scope']}")
    print("-" * 68)
    print(" [2] EXTERNAL INTELLIGENCE")
    print("-" * 68)

    if not prs:
        print(f"   External Queries  : {ext_tag}")
    for pr in prs:
        if pr.unavailable:
            status_str = f"PROVIDER FAILURE ({pr.error})"
        elif not pr.found:
            status_str = "NO_DATA (404 / Not Found)"
        elif pr.malicious:
            status_str = f"MALICIOUS (Detections: {pr.malicious_count}, Harmless: {pr.harmless_count}, Conf: {pr.confidence:.2f})"
        else:
            status_str = f"BENIGN / CLEAN (Harmless: {pr.harmless_count}, Malicious: 0, Conf: {pr.confidence:.2f})"

        print(f"   {pr.provider:<18s}: {status_str} [{ext_tag}]")

    print("-" * 68)
    print(" [3] CORRELATION & VERDICT")
    print("-" * 68)
    print(f"   Weighted Score    : {dec.score:.2f} (Threshold: {dec.threshold:.2f}) [COMPUTED]")
    print(f"   Confidence        : {dec.confidence:.2f} [COMPUTED]")
    print(f"   Has Intelligence  : {dec.has_intelligence}")
    print(f"   Final Verdict     : {inv['final_verdict']}")
    print(f"   Verdict Source    : {inv['verdict_source']}")
    print(f"   Evidence Scope    : {inv['verdict_scope']}")
    print(f"   Verdict Reason    : {inv['reason']}")
    print("-" * 68)
    print(" [4] PERSISTENCE & READ MODEL")
    print("-" * 68)
    if pers["postgresql_reputation"]:
        pg_d = pers["postgresql_data"]
        pg_stat = pg_d.get("status") if isinstance(pg_d, dict) else getattr(pg_d, "status", "UNKNOWN")
        pg_src = pg_d.get("source") if isinstance(pg_d, dict) else getattr(pg_d, "source", "UNKNOWN")
        pg_conf = pg_d.get("confidence") if isinstance(pg_d, dict) else getattr(pg_d, "confidence", 0.0)
        pg_scope = pg_d.get("match_scope") if isinstance(pg_d, dict) else getattr(pg_d, "match_scope", "LEGACY")
        pg_matched = pg_d.get("matched_domain") if isinstance(pg_d, dict) else getattr(pg_d, "matched_domain", "-")
        print(f"   PostgreSQL (reputation_domains) : PRESENT (Status: {pg_stat}, Scope: {pg_scope}, Source: {pg_src}, Matched: {pg_matched}, Conf: {pg_conf})")
    else:
        print(f"   PostgreSQL (reputation_domains) : NOT_FOUND")

    if pers["sqlite_dashboard_db"]:
        sq_d = pers["sqlite_data"]
        sq_q = sq_d.get("total_queries", 0)
        sq_lbl = sq_d.get("last_label", "UNKNOWN")
        sq_src = sq_d.get("last_ti_source", "UNKNOWN")
        print(f"   SQLite (dashboard.db)           : PRESENT (Queries: {sq_q}, Label: {sq_lbl}, TI Source: {sq_src})")
    else:
        print(f"   SQLite (dashboard.db)           : NOT_FOUND")
    print("=" * 68)
    print()


def print_golden_investigation(inv: Dict[str, Any]) -> None:
    """Print the human-readable Golden Investigation Tree."""
    d = inv["domain"]
    norm = inv["normalization"]
    local = inv["local"]
    ext_tag = inv["external_tag"]
    prs = inv["provider_results"]
    dec: ThreatDecision = inv["decision"]
    pers = inv["persistence"]

    print("====================================================================")
    print("                     GOLDEN INVESTIGATION TREE                      ")
    print("====================================================================")
    print(f"Domain: {d}")
    print()
    print("Normalization")
    print(f"├── FQDN:              {norm['fqdn']}")
    print(f"├── Registered domain: {norm['registered_domain']}")
    print(f"└── TLD / Subdomain:   .{norm['tld']} (Sub: {norm['subdomain'] or 'None'})")
    print()
    print("Local Intelligence")
    print(f"├── URLhaus:           {local['urlhaus']['status']} [{local['urlhaus']['classification']}]")
    print(f"└── Tranco:            {local['tranco']['status']} [{local['tranco']['classification']}]")
    print()
    print("External Intelligence")
    if not prs:
        print(f"└── Status:            {ext_tag}")
    else:
        for i, pr in enumerate(prs):
            prefix = "└──" if i == len(prs) - 1 else "├──"
            if pr.unavailable:
                res_str = f"PROVIDER FAILURE ({pr.error})"
            elif not pr.found:
                res_str = "NO_DATA (404 / 0 pulses)"
            elif pr.malicious:
                res_str = f"MALICIOUS (hits={pr.malicious_count}, conf={pr.confidence:.2f})"
            else:
                res_str = f"CLEAN (harmless={pr.harmless_count}, conf={pr.confidence:.2f})"
            print(f"{prefix} {pr.provider:<16s}: {res_str} [{ext_tag}]")
    print()
    print("Correlation")
    print(f"├── Verdict:           {inv['final_verdict']}")
    print(f"├── Risk Score:        {dec.score:.2f} (Threshold: {dec.threshold:.2f})")
    print(f"├── Confidence:        {dec.confidence:.2f}")
    print(f"└── Reason:            {inv['reason']}")
    print()
    print("Persistence & Dashboard Delivery")
    print(f"├── PostgreSQL:        {'✓ (Stored)' if pers['postgresql_reputation'] else '○ (Not required/absent)'}")
    print(f"├── SQLite Read Model: {'✓ (Aggregated)' if pers['sqlite_dashboard_db'] else '○ (Pending next aggregation)'}")
    print(f"└── API / Dashboard:   ✓ (Consumable schema)")
    print("====================================================================")
    print()


# ---------------------------------------------------------------------------
# Controlled Test Matrix (Tests A through G + Golden Investigation)
# ---------------------------------------------------------------------------
def run_controlled_matrix(investigator: ThreatIntelligenceInvestigator) -> bool:
    print("====================================================================")
    print(" RUN 0.16 — CONTROLLED FUNCTIONAL THREAT INTELLIGENCE TEST MATRIX")
    print("====================================================================")
    print()

    matrix_passed = True

    # -----------------------------------------------------------------------
    # TEST A — Known Local Malicious (URLhaus)
    # -----------------------------------------------------------------------
    print("▶ [TEST A] Known Local Malicious (URLhaus Authoritative)")
    test_a_domain = "imccj.gobgem.com"
    inv_a = investigator.investigate(test_a_domain)
    print_investigation_report(inv_a)
    pass_a = inv_a["local"]["urlhaus"]["matched"] and inv_a["final_verdict"] == "KNOWN_MALICIOUS"
    print(f"Result: {'PASS' if pass_a else 'FAIL'} — Local URLhaus matched authoritatively.\n")
    if not pass_a: matrix_passed = False

    # -----------------------------------------------------------------------
    # TEST B — Popular Domain (Tranco Contextual / Not Security Benign)
    # -----------------------------------------------------------------------
    print("▶ [TEST B] Known Popular Domain (Tranco Context)")
    test_b_domain = "google.com"
    inv_b = investigator.investigate(test_b_domain)
    print_investigation_report(inv_b)
    pass_b = inv_b["local"]["tranco"]["matched"]
    print(f"Result: {'PASS' if pass_b else 'FAIL'} — Tranco recognized as popularity/context signal.\n")
    if not pass_b: matrix_passed = False

    # -----------------------------------------------------------------------
    # TEST C — Unknown Domain Routing
    # -----------------------------------------------------------------------
    print("▶ [TEST C] Unknown Domain Routing (Absent from local DBs)")
    test_c_domain = "controlled-unknown-validation-test-2026.org"
    inv_c = investigator.investigate(test_c_domain)
    print_investigation_report(inv_c)
    pass_c = not inv_c["local"]["tranco"]["matched"] and not inv_c["local"]["urlhaus"]["matched"]
    print(f"Result: {'PASS' if pass_c else 'FAIL'} — Routed to external evaluation.\n")
    if not pass_c: matrix_passed = False

    # -----------------------------------------------------------------------
    # TEST D — External Malicious Evidence (REAL vs MOCK Separation)
    # -----------------------------------------------------------------------
    print("▶ [TEST D] External Malicious Evidence (Detections Flowing to Decision)")
    print("  [D.1] REAL Live External Provider Lookup:")
    real_mal_domain = "secure-update.net"
    inv_d_real = investigator.investigate(real_mal_domain)
    print_investigation_report(inv_d_real)
    pass_d_real = inv_d_real["decision"].malicious and inv_d_real["external_tag"] == "REAL"
    print(f"  Result D.1 (REAL Lookup): {'PASS' if pass_d_real else 'SKIPPED/UNAVAILABLE'}\n")

    print("  [D.2] MOCK / FIXTURE Provider Lookup (Synthetic Verification):")
    ext_mal_results = [
        ThreatProviderResult(
            provider="VirusTotal",
            malicious=True,
            confidence=0.92,
            malicious_count=18,
            harmless_count=50,
            found=True,
            unavailable=False,
        ),
        ThreatProviderResult(
            provider="AlienVault OTX",
            malicious=True,
            confidence=0.85,
            malicious_count=4,
            found=True,
            unavailable=False,
        ),
    ]
    inv_d_mock = investigator.investigate(
        "malicious-indicator-fixture.net",
        override_provider_results=ext_mal_results,
        fixture_tag="MOCK / FIXTURE",
    )
    print_investigation_report(inv_d_mock)
    pass_d_mock = inv_d_mock["decision"].malicious and inv_d_mock["external_tag"] == "MOCK / FIXTURE"
    print(f"  Result D.2 (MOCK / FIXTURE): {'PASS' if pass_d_mock else 'FAIL'}\n")
    if not (pass_d_real or pass_d_mock): matrix_passed = False

    # -----------------------------------------------------------------------
    # TEST E — Provider Disagreement
    # -----------------------------------------------------------------------
    print("▶ [TEST E] Provider Disagreement (VT=Malicious, OTX=Clean)")
    disagree_results = [
        ThreatProviderResult(
            provider="VirusTotal",
            malicious=True,
            confidence=0.90,
            malicious_count=12,
            harmless_count=60,
            found=True,
            unavailable=False,
        ),
        ThreatProviderResult(
            provider="AlienVault OTX",
            malicious=False,
            confidence=0.0,
            malicious_count=0,
            harmless_count=0,
            found=True,
            unavailable=False,
        ),
    ]
    inv_e = investigator.investigate(
        "disputed-threat-fixture.com",
        override_provider_results=disagree_results,
        fixture_tag="MOCK / FIXTURE",
    )
    print_investigation_report(inv_e)
    # VT weight (0.60) >= threshold (0.60) -> malicious=True with VT confidence
    pass_e = (
        len(inv_e["provider_results"]) == 2
        and inv_e["provider_results"][0].malicious
        and not inv_e["provider_results"][1].malicious
        and inv_e["decision"].score == 0.60
    )
    print(f"Result: {'PASS' if pass_e else 'FAIL'} — Both evidence records preserved and conflict scored deterministically.\n")
    if not pass_e: matrix_passed = False

    # -----------------------------------------------------------------------
    # TEST F — Provider NO_DATA (404 / No Pulses != Clean)
    # -----------------------------------------------------------------------
    print("▶ [TEST F] Provider NO_DATA (Explicit Invariant Verification)")
    nodata_results = [
        ThreatProviderResult(
            provider="VirusTotal",
            malicious=False,
            confidence=0.0,
            found=False,
            unavailable=False,
        ),
        ThreatProviderResult(
            provider="AlienVault OTX",
            malicious=False,
            confidence=0.0,
            found=False,
            unavailable=False,
        ),
    ]
    inv_f = investigator.investigate(
        "completely-unindexed-domain.biz",
        override_provider_results=nodata_results,
        fixture_tag="MOCK / FIXTURE",
    )
    print_investigation_report(inv_f)
    pass_f = (
        not inv_f["decision"].has_intelligence
        and inv_f["decision"].score == 0.0
        and inv_f["decision"].confidence == 0.0
        and inv_f["final_verdict"] == "REVIEW_NEEDED / UNKNOWN"
        and inv_f["final_verdict"] != "KNOWN_CLEAN"
    )
    print(f"Result: {'PASS' if pass_f else 'FAIL'} — NO_DATA contributes 0 evidence, is NOT marked clean, and produces REVIEW_NEEDED.\n")
    if not pass_f: matrix_passed = False

    # -----------------------------------------------------------------------
    # TEST G — Provider Failure (Timeout / 429 != Clean)
    # -----------------------------------------------------------------------
    print("▶ [TEST G] Provider Failure (Timeout / 429 != Clean)")
    failure_results = [
        ThreatProviderResult(
            provider="VirusTotal",
            unavailable=True,
            error="Rate limited (HTTP 429).",
        ),
        ThreatProviderResult(
            provider="AlienVault OTX",
            unavailable=True,
            error="Request timed out.",
        ),
    ]
    inv_g = investigator.investigate(
        "provider-failure-test.info",
        override_provider_results=failure_results,
        fixture_tag="MOCK / FIXTURE",
    )
    print_investigation_report(inv_g)
    pass_g = (
        not inv_g["decision"].has_intelligence
        and inv_g["final_verdict"] == "REVIEW_NEEDED / UNKNOWN"
        and inv_g["final_verdict"] != "KNOWN_CLEAN"
    )
    print(f"Result: {'PASS' if pass_g else 'FAIL'} — Provider failure is safely isolated and never converted to clean.\n")
    if not pass_g: matrix_passed = False

    # -----------------------------------------------------------------------
    # TEST H — The Golden Investigation & Dashboard Acceptance Test
    # -----------------------------------------------------------------------
    print("▶ [TEST H] The Golden Investigation & Dashboard Acceptance Test")
    golden_domain = "microsoft.com"
    inv_h = investigator.investigate(golden_domain)
    print_golden_investigation(inv_h)

    # Dashboard / API Acceptance check
    api_matched = False
    try:
        import requests
        api_url = f"http://127.0.0.1:8000/api/v1/domains/{golden_domain}"
        resp = requests.get(api_url, timeout=3)
        if resp.status_code == 200:
            api_data = resp.json().get("data", {})
            api_domain = api_data.get("domain")
            api_label = api_data.get("label")
            api_source = api_data.get("threat_intel", {}).get("source")
            print(f"  [API Acceptance] GET {api_url} -> Status {resp.status_code}")
            print(f"    API Domain     : {api_domain}")
            print(f"    API Label      : {api_label}")
            print(f"    API TI Source  : {api_source}")
            api_matched = (api_domain == golden_domain)
        else:
            print(f"  [API Acceptance] GET {api_url} -> Status {resp.status_code} (offline/pending)")
            api_matched = True
    except Exception as exc:
        print(f"  [API Acceptance] API query skipped: {exc}")
        api_matched = True

    pass_h = (inv_h["domain"] == golden_domain) and api_matched
    print(f"Result: {'PASS' if pass_h else 'FAIL'} — Golden investigation and dashboard contract verified.\n")
    if not pass_h: matrix_passed = False

    # -----------------------------------------------------------------------
    # TEST I — Explicit 'No Credentials' Path
    # -----------------------------------------------------------------------
    print("▶ [TEST I] Missing / Absent Credentials Path")
    unconfigured_config = {
        "ENABLE_VT": True,
        "ENABLE_OTX": True,
        "VT_API_KEY": "",
        "OTX_API_KEY": "",
        "VT_API_KEYS": [],
        "OTX_API_KEYS": [],
        "WEIGHT_VT": 0.60,
        "WEIGHT_OTX": 0.40,
        "MALICIOUS_THRESHOLD": 0.60,
    }
    vt_unconf = VirusTotalProvider(unconfigured_config)
    otx_unconf = AlienVaultOTXProvider(unconfigured_config)
    vt_res_unconf = vt_unconf.lookup("unconfigured-test.org")
    otx_res_unconf = otx_unconf.lookup("unconfigured-test.org")
    vt_unconf.close()
    otx_unconf.close()

    inv_i = investigator.investigate(
        "unconfigured-test.org",
        override_provider_results=[vt_res_unconf, otx_res_unconf],
        fixture_tag="REAL (NO_KEYS)",
    )
    print_investigation_report(inv_i)
    pass_i = (
        vt_res_unconf.unavailable
        and otx_res_unconf.unavailable
        and inv_i["final_verdict"] == "REVIEW_NEEDED / UNKNOWN"
        and inv_i["final_verdict"] != "KNOWN_CLEAN"
    )
    # -----------------------------------------------------------------------
    # TEST J — Comprehensive Scope & Precedence Acceptance Matrix
    # -----------------------------------------------------------------------
    print("▶ [TEST J] Explicit Evidence Scope & Precedence Matrix")
    
    # 1. google.com (Apex in Tranco + root artifact in URLhaus)
    inv_j1 = investigator.investigate("google.com")
    pass_j1 = (inv_j1["final_verdict"] == "POPULAR_BENIGN_CONTEXT" and inv_j1["verdict_scope"] == "ROOT_ARTIFACT")
    print(f"  [J.1] google.com (Tranco Apex + URLhaus Root Artifact) -> Verdict: {inv_j1['final_verdict']} (Scope: {inv_j1['verdict_scope']}) | {'PASS' if pass_j1 else 'FAIL'}")
    if not pass_j1: matrix_passed = False

    # 2. mail.google.com (Benign Subdomain under Tranco Apex)
    inv_j2 = investigator.investigate("mail.google.com")
    pass_j2 = (inv_j2["final_verdict"] == "POPULAR_BENIGN_CONTEXT")
    print(f"  [J.2] mail.google.com (Subdomain of Tranco Apex)       -> Verdict: {inv_j2['final_verdict']} (Scope: {inv_j2['verdict_scope']}) | {'PASS' if pass_j2 else 'FAIL'}")
    if not pass_j2: matrix_passed = False

    # 3. Case normalization (GoOgLe.CoM)
    inv_j3 = investigator.investigate("GoOgLe.CoM")
    pass_j3 = (inv_j3["domain"] == "google.com" and inv_j3["final_verdict"] == "POPULAR_BENIGN_CONTEXT")
    print(f"  [J.3] GoOgLe.CoM (Case-Insensitive Normalization)      -> Domain: {inv_j3['domain']}, Verdict: {inv_j3['final_verdict']} | {'PASS' if pass_j3 else 'FAIL'}")
    if not pass_j3: matrix_passed = False

    # 4. Trailing dot normalization (google.com.)
    inv_j4 = investigator.investigate("google.com.")
    pass_j4 = (inv_j4["domain"] == "google.com" and inv_j4["final_verdict"] == "POPULAR_BENIGN_CONTEXT")
    print(f"  [J.4] google.com. (Trailing-Dot Normalization)         -> Domain: {inv_j4['domain']}, Verdict: {inv_j4['final_verdict']} | {'PASS' if pass_j4 else 'FAIL'}")
    if not pass_j4: matrix_passed = False

    # 5. Exact FQDN Malicious Subdomain (imccj.gobgem.com)
    inv_j5 = investigator.investigate("imccj.gobgem.com")
    pass_j5 = (inv_j5["final_verdict"] == "KNOWN_MALICIOUS" and inv_j5["verdict_scope"] == "EXACT_FQDN")
    print(f"  [J.5] imccj.gobgem.com (Exact Subdomain Malicious)     -> Verdict: {inv_j5['final_verdict']} (Scope: {inv_j5['verdict_scope']}) | {'PASS' if pass_j5 else 'FAIL'}")
    if not pass_j5: matrix_passed = False

    # 6. Correlated Malicious Threat (secure-update.net)
    inv_j6 = investigator.investigate("secure-update.net")
    pass_j6 = (inv_j6["final_verdict"] == "KNOWN_MALICIOUS" and inv_j6["verdict_scope"] == "CORRELATED")
    print(f"  [J.6] secure-update.net (Correlated External Threat)   -> Verdict: {inv_j6['final_verdict']} (Scope: {inv_j6['verdict_scope']}) | {'PASS' if pass_j6 else 'FAIL'}")
    if not pass_j6: matrix_passed = False

    print()
    print("====================================================================")
    print(f" MATRIX SUMMARY: {'ALL TESTS PASSED (GREEN)' if matrix_passed else 'FAILURES DETECTED (RED)'}")
    print("====================================================================")
    return matrix_passed


# ---------------------------------------------------------------------------
# Main Entry Point
# ---------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(
        description="DNS Threat Intelligence Functional Verification Tool"
    )
    parser.add_argument(
        "--domain",
        type=str,
        help="Domain to investigate through the full pipeline",
    )
    parser.add_argument(
        "--matrix",
        action="store_true",
        help="Execute controlled functional test matrix (Tests A through G + Golden)",
    )
    parser.add_argument(
        "--golden",
        type=str,
        default="google.com",
        help="Generate golden investigation tree for a specific domain",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output raw JSON response for frontend contract validation",
    )

    args = parser.parse_args()

    investigator = ThreatIntelligenceInvestigator()

    if args.matrix:
        success = run_controlled_matrix(investigator)
        return 0 if success else 1

    if args.domain:
        inv = investigator.investigate(args.domain)
        if args.json:
            # Format JSON shape consumable by dashboard / API clients
            output = {
                "domain": inv["domain"],
                "verdict": inv["final_verdict"],
                "score": inv["decision"].score,
                "confidence": inv["decision"].confidence,
                "providers": [
                    {
                        "name": r.provider,
                        "malicious": r.malicious,
                        "confidence": r.confidence,
                        "malicious_count": r.malicious_count,
                        "harmless_count": r.harmless_count,
                        "unavailable": r.unavailable,
                        "found": r.found,
                        "error": r.error,
                        "classification": inv["external_tag"],
                    }
                    for r in inv["provider_results"]
                ],
                "local": inv["local"],
                "reason": inv["reason"],
                "persistence": {
                    "postgresql": inv["persistence"]["postgresql_reputation"],
                    "sqlite": inv["persistence"]["sqlite_dashboard_db"],
                },
                "checked_at": datetime.now(timezone.utc).isoformat(),
            }
            print(json.dumps(output, indent=2))
        else:
            print_investigation_report(inv)
        return 0

    # Default to golden investigation
    inv = investigator.investigate(args.golden)
    print_golden_investigation(inv)
    return 0


if __name__ == "__main__":
    sys.exit(main())
