"use client";

import React from "react";
import { useRouter } from "next/navigation";
import { VerdictBadge } from "@/components/security/VerdictBadge";
import { formatFullTimestamp } from "@/lib/format";
import { ClientActivityLogItem } from "@/types/api";

interface ClientActivityTableProps {
  recentActivity?: ClientActivityLogItem[];
}

export const ClientActivityTable: React.FC<ClientActivityTableProps> = ({
  recentActivity = [],
}) => {
  const router = useRouter();

  return (
    <div className="bg-card border border-border/70 rounded-lg shadow-2xs overflow-hidden">
      {/* Card Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border/50">
        <div>
          <h2 className="text-[13px] font-semibold text-foreground tracking-tight">
            Recent Queries
          </h2>
          <p className="text-[11px] text-muted-foreground mt-0.5">
            Chronological DNS query events generated by this endpoint
          </p>
        </div>
        <span className="text-[11px] text-muted-foreground font-mono bg-muted/40 px-2 py-0.5 rounded">
          {recentActivity.length} {recentActivity.length === 1 ? "query" : "queries"}
        </span>
      </div>

      {/* Table Content - strictly content-sized, zero top gap */}
      {recentActivity.length === 0 ? (
        <div className="py-8 text-center text-xs text-muted-foreground">
          No recent queries found
        </div>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-xs text-left">
            <thead className="bg-muted/30 text-muted-foreground border-b border-border/50">
              <tr>
                <th className="px-4 py-2.5 font-medium">Timestamp</th>
                <th className="px-4 py-2.5 font-medium">Domain</th>
                <th className="px-4 py-2.5 font-medium">Type</th>
                <th className="px-4 py-2.5 font-medium text-right">Verdict</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/40">
              {recentActivity.map((log, idx) => (
                <tr
                  key={`${log.timestamp}-${log.domain}-${idx}`}
                  onClick={() =>
                    router.push(
                      `/investigate/domains/${encodeURIComponent(log.domain)}`,
                    )
                  }
                  className="hover:bg-muted/30 cursor-pointer transition-colors group"
                >
                  <td className="px-4 py-2.5 text-muted-foreground text-[11px] font-mono whitespace-nowrap">
                    {formatFullTimestamp(log.timestamp)}
                  </td>
                  <td className="px-4 py-2.5 font-mono font-medium text-foreground group-hover:text-primary transition-colors truncate max-w-[200px]">
                    {log.domain}
                  </td>
                  <td className="px-4 py-2.5 font-mono text-muted-foreground text-[11px]">
                    {log.query_type || "A"}
                  </td>
                  <td className="px-4 py-2.5 text-right">
                    <VerdictBadge verdict={log.final_label} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default ClientActivityTable;
