
import logging
import sys
from pathlib import Path
from typing import List

# Add the project root to Python path so imports work from any directory
sys.path.insert(0, str(Path(__file__).parent))

# Import our parser components
from parser.parser import DNSLogParser, ParseResult
from parser.models import DNSRecord

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)-8s] %(name)s: %(message)s",
    datefmt="%H:%M:%S"
)

logging.getLogger("parser.parser").setLevel(logging.WARNING)
logging.getLogger("parser.validators").setLevel(logging.WARNING)

logger = logging.getLogger("main")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1: Parse all log file formats
# ─────────────────────────────────────────────────────────────────────────────

def demonstrate_parsing() -> List[DNSRecord]:
    """
    Demonstrate parsing the normalized CSV produced by the Bind Converter.

    Returns:
        List[DNSRecord]: All parsed DNS records.
    """

    print("\n" + "=" * 70)
    print("  DNS LOG PARSER — CYBERSECURITY THREAT DETECTION PROJECT")
    print("=" * 70)

    # Create parser
    parser = DNSLogParser(strict_mode=False)

    all_records: List[DNSRecord] = []

    print("\n📊 Parsing normalized CSV generated by Bind Converter...")

    try:
        csv_result = parser.parse_file("normalized_dns_dataset.csv")
        all_records.extend(csv_result.records)
        print(csv_result.summary())

    except FileNotFoundError as e:
        print(f"  ⚠ {e}")

    print(f"\n✅ Total records loaded into memory: {len(all_records)}")

    return all_records

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2: Display parsed records
# ─────────────────────────────────────────────────────────────────────────────

def display_parsed_records(records: List[DNSRecord]) -> None:
    """
    Print all parsed DNS records in a readable format.

    Shows how to iterate over parsed records and access individual fields.

    Args:
        records: List of DNSRecord objects.
    """
    print("\n" + "="*70)
    print("  PARSED DNS RECORDS")
    print("="*70)
    print(f"{'#':<4} {'Timestamp':<22} {'Client IP':<16} {'Domain':<35} {'Type':<6} {'Code':<10} {'Resolved IP':<18} {'TTL'}")
    print("-"*130)

    for idx, record in enumerate(records, start=1):
        # Access fields using dot notation (because DNSRecord is a dataclass)
        print(
            f"{idx:<4} "
            f"{record.timestamp.strftime('%Y-%m-%d %H:%M:%S'):<22} "
            f"{record.client_ip:<16} "
            f"{record.domain:<35} "
            f"{record.query_type:<6} "
            f"{record.response_code:<10} "
            f"{record.resolved_ip or 'N/A':<18} "
            f"{record.ttl if record.ttl is not None else 'N/A'}"
        )

    print("-"*130)
    print(f"Total: {len(records)} records")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3: Demonstrate filtering and querying
# ─────────────────────────────────────────────────────────────────────────────

def demonstrate_filtering(records: List[DNSRecord]) -> None:
    """
    Show how to filter and query parsed DNS records.

    This demonstrates the kinds of queries a Feature Extraction Engine
    would run on parsed records.

    Args:
        records: List of DNSRecord objects to filter.
    """
    print("\n" + "="*70)
    print("  RECORD FILTERING EXAMPLES")
    print("="*70)

    # ── Filter 1: Failed queries (NXDOMAIN, SERVFAIL, etc.) ───────────────────
    failed_queries = [r for r in records if r.is_failed_query()]
    print(f"\n🔴 Failed queries (NXDOMAIN/SERVFAIL/etc.): {len(failed_queries)}")
    for r in failed_queries:
        print(f"   {r}")

    # ── Filter 2: Queries from internal (private) IPs ─────────────────────────
    internal_queries = [r for r in records if r.is_private_client()]
    print(f"\n🏠 Queries from internal IPs: {len(internal_queries)}")

    # ── Filter 3: Queries by type ──────────────────────────────────────────────
    type_counts: dict = {}
    for record in records:
        type_counts[record.query_type] = type_counts.get(record.query_type, 0) + 1

    print(f"\n📊 Query type breakdown:")
    for qtype, count in sorted(type_counts.items(), key=lambda x: -x[1]):
        bar = "█" * count
        print(f"   {qtype:<8} : {count:>3}  {bar}")

    # ── Filter 4: Unique domains queried ──────────────────────────────────────
    unique_domains = {r.domain for r in records}
    print(f"\n🌐 Unique domains queried: {len(unique_domains)}")
    for domain in sorted(unique_domains):
        print(f"   • {domain}")

    # ── Filter 5: Unique client IPs ────────────────────────────────────────────
    unique_clients = {r.client_ip for r in records}
    print(f"\n💻 Unique client IPs: {len(unique_clients)}")
    for ip in sorted(unique_clients):
        client_records = [r for r in records if r.client_ip == ip]
        nxdomain_count = sum(1 for r in client_records if r.response_code == "NXDOMAIN")
        print(f"   {ip:<16} — {len(client_records)} queries, {nxdomain_count} NXDOMAIN")

    # ── Filter 6: Low TTL records (potentially suspicious) ────────────────────
    low_ttl_records = [r for r in records if r.ttl is not None and r.ttl < 10]
    print(f"\n⏱  Very low TTL records (TTL < 10s): {len(low_ttl_records)}")
    for r in low_ttl_records:
        print(f"   TTL={r.ttl}s | {r.client_ip} → {r.domain}")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4: Convert to dict format
# ─────────────────────────────────────────────────────────────────────────────

def demonstrate_dict_conversion(records: List[DNSRecord]) -> None:
    """
    Show how to convert DNSRecord objects back to dictionaries.

    This is important because downstream systems (databases, JSON APIs,
    pandas DataFrames) often expect plain dictionaries, not dataclass objects.

    Args:
        records: List of DNSRecord objects.
    """
    print("\n" + "="*70)
    print("  CONVERTING TO DICT FORMAT")
    print("="*70)

    if not records:
        print("No records to show.")
        return

    # Take the first record as an example
    first_record = records[0]

    print(f"\n🔷 DNSRecord object (dataclass):")
    print(f"   {first_record}")

    print(f"\n🔷 Same record as Python dict (via .to_dict()):")
    record_dict = first_record.to_dict()

    import json
    print(json.dumps(record_dict, indent=4))

    print(f"\n🔷 All records as list of dicts:")
    all_dicts = [r.to_dict() for r in records]
    print(f"   Generated {len(all_dicts)} dicts. First entry keys: {list(all_dicts[0].keys())}")



def main():
    # Step 1: Parse all log files
    all_records = demonstrate_parsing()


    print("\n" + "=" * 70)
    print("  PARSING COMPLETE")
    print(f"  {len(all_records)} DNS records ready for feature extraction.")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    main()